application:
  name: DecemberEssayBot
datasource:
  url: ${DATASOURCE_URL}
  username: ${DATASOURCE_USERNAME}
  password: ${DATASOURCE_PASSWORD}
  driver-class-name: org.hibernate.dialect.PostgreSQLDialect
jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
    ddl-auto: update
profiles:
  active: prod
server:
  port: 8080
bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}
  api-key: ${BOT_API_KEY}
