spring:
  application:
    name: DecemberEssayBot
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
server:
  port: 8080
bot:
  name: december_essay_bot
  token: ${BOT_TOKEN}
  api-key: ${BOT_API_KEY}
