application:
  name: DecemberEssayBot
datasource:
  url: jdbc:postgresql://db:5432/essay_bot_database
  username: postgres
  password: ${DATASOURCE_PASSWORD}
  driver-class-name: org.hibernate.dialect.PostgreSQLDialect
jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
    ddl-auto: update
profiles:
  active: prod
server:
  port: 8080
bot:
  name: december_essay_bot
  token: ${BOT_TOKEN}
  api-key: ${BOT_API_KEY}
